### ISSUE TITLE
Bump Node version from 16 to 20

### ISSUE THREAD

**Issue by jcfilo** [Kong/setup-deck#11]
Hi Guys!

Any chance we could get a new release using Node v20 please. Seeing too many of these warnings in my workflow runs

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: kong/setup-deck@v1.5.`

Thanks

**Comment by mheap** [comment]
v1.6.0 is out and uses `node20`

**Comment by jcfilo** [comment]
thank you!
