### ISSUE TITLE
Bump version of node up from 12?

### ISSUE THREAD

**Issue by mark-sivill-kong** [Kong/setup-deck#6]
Hi,

Could we bump the version of node used in this setup-deck to later than 12 which is now end-of-life (https://endoflife.date/nodejs) ?

I'm trying to create a github action and get the following warning when using node 18...

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: kong/setup-deck@v1.2.1

Github Action snippet...

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Node version
        run: node --version

      - name: Install decK
        uses: kong/setup-deck@v1.2.1
  
Thanks

Mark

**Comment by mark-sivill-kong** [comment]
As a work around something like the following could also be used

Github Action snippet...

```
     - name: Install decK
        run: |
          curl -sL https://github.com/Kong/deck/releases/download/v1.16.1/deck_1.16.1_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz
          rm deck.tar.gz
          mv deck /usr/local/bin/ 
          deck version
```

**Comment by mheap** [comment]
This should be resolved now. I just tagged a new release which uses node 16 by default
